<div style="color:white;
           display:fill;
           border-radius:5px;
           background-color:#5642C5;
           font-size:200%;
           font-\amily:Arial;letter-spacing:0.5px">

<p width = 20%, style="padding: 10px;
              color:white;">
Object Oriented Programming
              
</p>
</div>

Data Science Cohort Live NYC Feb 2022
<p>Phase 3: Topic 21</p>
<br>
<br>

<div align = "right">
<img src="Images/flatiron-school-logo.png" align = "right" width="200"/>
</div>

#### Objected Oriented Programming

- We've actually been using this without realizing it.


#### Examples

- results object in statsmodels OLS fit
- requests object or BeautifulSoup objects in web scraping
- sklearn LinearRegression models
- fig and ax objects in Matplotlib

#### Object Oriented Program in a Nutshell

<center><img src = "Images/pikachu.png" width = 800 /></center>

- Class: Pokemon
- object instance of Pokemon class

- Attributes = Fields. Properties of object instance.
- Methods: an action. Can change state of object instance.

<center><img src = "Images/pikachu.png" width = 800 /></center>

-  **Class**: general class of similar objects
- Want common attributes/methods for each instantiated object

**Pokemon is general class. Pikachu is an object of class Pokemon.**

<center><img src = "Images/pikachu.png" width = 800 /></center>

**Fields/Attributes**:
- objects of same class share same attributes
- each attribute takes on different values for different instantiations.
    
e.g., Name, Type, Health attributes common to all pokemons


But Pikachu and Bulbasaur:
- different values of attributes.

<center><img src = "Images/pikachu.png" width = 800 /></center>

**Methods**:
- Objects in given Class can execute common set of functions
- Functions can change internal state of object
    - i.e. change attributes: .evolve() can change health, name, etc.

#### Creating a class in Python

Create simple class using class constructor and initialization:

In [2]:
class Pokemon:

    def __init__(self, name, lvl, health, attack_points, defense_points):
        
        self.name = name
        self.level = lvl
        self.life = health
        self.attack_power = attack_points
        self.defense_points = defense_points
        

the __init__ method is a special function:

- the first argument is always: *self*
- *self* refers to specific instance of class. 
- the other arguments: initalization arguments 
    - user specified inputs in initializing instance.
    - can have default arguments


In [3]:
class Pokemon:
    
    def __init__(self, name, lvl, health, attack_points, defense_points):
        
        self.name = name
        self.level = lvl
        self.life = health
        self.attack_power = attack_points
        self.defense_points = defense_points
        

#### Let's see this in action 

Create an instance of a Pokemon:
- Create and instantiate a Pikachu.

In [4]:
pikachu = Pokemon('Pikachu', 2, 70, 7, 4)

Let's check out some of the attributes

In [5]:
pikachu.attack_power

7

In [6]:
class Pokemon:
    
    def __init__(self, name, lvl, health, attack_points, defense_points):
        
        self.name = name
        self.level = lvl
        self.life = health
        self.attack_power = attack_points
        self.defense_points = defense_points

- So far the class object is like a grouping of variables (like a dict). 
- Adding methods give class objects a richer structure

#### Methods

- Create functions that:
    - return object state
    - update object state (i.e. change internal attributes)
    - do it based on information external to object.


In [17]:
class Pokemon:
    
    def __init__(self, name, lvl, health, attack_points, defense_points):
        
        self.name = name
        self.level = lvl
        self.life = health
        self.attack_power = attack_points
        self.defense_points = defense_points
    
    def get_state(self):
        
        state_dict = {'name': self.name, 'level': self.level, 'life': self.life,
                     'attack': self.attack_power, 'defense': self.defense_points}
        return state_dict
        
    def evolve(self, evolved_name):
        #Change Pokemon name to given evolved name state
        self.name = evolved_name
        
        #level up the stats
        self.level += 1
        self.life += 30
        self.attack_power += 4
        self.defense_points += 3

In [18]:
pikachu = Pokemon('Pikachu', 2, 70, 7, 4)

In [19]:
pikachu.get_state()

{'name': 'Pikachu', 'level': 2, 'life': 70, 'attack': 7, 'defense': 4}

<img src = "Images/evolution_phases.jpeg" width = 700 />

In [20]:
pikachu.evolve('Raichu')

In [21]:
pikachu.get_state()

{'name': 'Raichu', 'level': 3, 'life': 100, 'attack': 11, 'defense': 7}

In [15]:
pikachu.evolve('Alolan Raichu')

In [16]:
pikachu.get_state()

{'name': 'Alolan Raichu', 'level': 4, 'life': 130, 'attack': 15, 'defense': 10}

Let's have fun with another class:
- Create a koala class with each instance a koala that eats bunches of eucalyptus and poops.
- Each bunch of eucalyptus weighs a pound.
- Pooping gets rid of half a pound.
- If the load in the koala's belly goes past 6 pounds:
    - the koala dies by belly explosion.

<center><img src = "Images/gastro.jpg" width = 1000/></center>

Your data science instructor really doesn't get this objected oriented programming stuff! Help him out.

In [24]:
class Koala:
    
    # first need to initialize. 
    #define relevant variables.
    def __init__(self, belly_weight, name, alive = 'Alive'):
        self.weight = belly_weight
        self.name = name
        self.status = alive
    # create eat_eucalyptus() method
    def alive_status(self):
        if self.weight > 6:
            self.status = 'Dead'
        else:
            pass
        return self.status
            
    def eat_eucalyptus(self, num_bunches = 1):
        if self.status == 'Alive':
            self.weight += num_bunches
        else:
            print("Dead koalas dont eat")
        

    # create poop() method
    def poop(self, poop_weight = 0.5):
        if self.status == 'Alive':
            self.weight -= poop_weight
        else:
            print("Dead koalas don't poop.")

In [29]:
koala1 = Koala(2, 'Randy')
koala1.eat_eucalyptus()

In [46]:
koala1.eat_eucalyptus(8)

In [47]:
koala1.alive_status()

'Alive'

In [48]:
koala1.weight

5.5

In [42]:
koala1.poop()


- Each bunch of eucalyptus weighs a pound.
- Pooping gets rid of half a pound.
- If the load in the koala's belly goes past 6 pounds:
    - the koala dies by belly explosion.

Now for why all this is relevant to our work in data science.

In [49]:
class Standardizer:
    
    def __init__(self):
        self.mean_series = None
        self.stdev_series = None
    
    def fit(self, data):
        self.mean_series = data.mean()
        self.stdev_series = data.std(ddof = 1)
        
    def transform(self, X):
        X_standard = (X - self.mean_series)/self.stdev_series 
        return X_standard
    
    def fit_transform(self, X):
        #fit with X
        self.fit(X)
        #apply transformation to X
        transformed = self.transform(X)
        return transformed      

In [50]:
import pandas as pd
heart_df = pd.read_csv('Data/heart.csv', usecols = ['age', 'chol', 'thalach', 'target'])
heart_df.head()

age  chol  thalach  target
0   63   233      150       1
1   37   250      187       1
2   41   204      172       1
3   56   236      178       1
4   57   354      163       1

Split into train and test sets.

In [51]:
from sklearn.model_selection import train_test_split
X = heart_df.drop(columns = ['target'])
y = heart_df['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

Let's use our standardizer class! 
- Instantiate transformer object.
- Fit our standardizer object to the training set.

In [52]:
sd = Standardizer()

In [53]:
sd.mean_series

In [54]:
sd.stdev_series

Fit the transformer.

In [55]:
sd.fit(X_train)

In [56]:
sd.mean_series

age         54.268595
chol       242.628099
thalach    149.136364
dtype: float64

In [57]:
sd.stdev_series

age         8.695289
chol       47.947003
thalach    23.395969
dtype: float64

Means and standard deviations for each column:
- extracted (fit) from training set.
- use these parameters to transform both train and test

#### Transform train set

In [60]:
X_train_standard = sd.transform(X_train)
X_train_standard.head()

age      chol   thalach
154 -1.755962 -0.471940  0.122399
28   1.234163  3.636763  0.336111
282  0.544134 -0.513653 -0.646965
35  -0.950928 -1.368763  0.464338
65  -2.215981 -1.243625  1.404671

In [59]:
X_train_standard.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 242 entries, 154 to 252
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   age      242 non-null    float64
 1   chol     242 non-null    float64
 2   thalach  242 non-null    float64
dtypes: float64(3)
memory usage: 7.6 KB


In [66]:
X_train_standard.std()

age        1.0
chol       1.0
thalach    1.0
dtype: float64

#### Transform test set
- Use fitted parameters to transform test set.

In [69]:
X_test_standard = sd.transform(X_test)
X_test_standard.head()

age      chol   thalach
172  0.429129  0.862867  0.464338
40  -0.375904  1.363420 -0.305025
95  -0.145895 -0.346802 -1.630040
285 -0.950928  1.425989 -1.245358
129  2.269206  0.550022 -1.202616

In [70]:
X_test_standard.std()

age        1.213224
chol       1.322835
thalach    0.893399
dtype: float64

Scikit-learn transformers are instances of class objects.

In [71]:
from sklearn.preprocessing import StandardScaler
sklearn_sd = StandardScaler()

X_train_sklearn = sklearn_sd.fit_transform(X_train)

In [73]:
sklearn_sd.mean_

array([ 54.26859504, 242.62809917, 149.13636364])

In [74]:
sklearn_sd.scale_

array([ 8.67730519, 47.84783599, 23.34758026])

Looking at the desciptive statistics of the transformed $X_{train}$:

In [75]:
print(X_train_sklearn.mean(axis = 0))

[ 4.58769845e-17 -5.13822226e-17  4.40419051e-16]


In [76]:
print(X_train_sklearn.std(axis = 0))

[1. 1. 1.]


Yeah, its doing the same thing as our hard-coded class.

#### Models in scikit-learn
- Also classes with different methods.
- .fit()
- .predict()
- .fit_predict()
- .score(X,y)

LinearRegression() was an example.

In [77]:
from numpy import linalg # linear algebra subpackage
import numpy as np

Implementing custom OLS linear regression class:
- sklearn model doing similar things under hood of
    - .fit(X,y) method
    - .predict(X) method
    - etc.

In [80]:
class CustomLinearRegression:
    
    def __init__(self):
        self.intercept = None
        self.coeff = None
        
    def fit(self, X_in, y):
        
        #create a column of 1s for offset fitting
        bias_col = np.ones(X_in.shape[0]).reshape(-1,1) 
    
        #augmented data matrix with column of ones
        X = np.hstack((bias_col, X_in))
        
        # weights: result of least squares minimization
        w = linalg.inv(X.T@X)@(X.T@y)
        # its a formula
        
        self.intercept = w[0]
        self.coeff = w[1::]
        
    # same as y = beta_0 + beta_1*x_1 + beta_2*x_2 + ... + beta_n*x_n
    #just more compact. we'll see later.
    def predict(self, X):
        y_pred = X@self.coeff + self.intercept
        return y_pred
    

Create instances of our custom model and scikit-learn linear regression model

In [91]:
from sklearn.linear_model import LinearRegression
clr = CustomLinearRegression()
sklearn_lr = LinearRegression()

Scikit-learn linear regression .fit() method:
- find weights/model parameters

In [92]:
clr.fit(X_train, y_train)
sklearn_lr.fit(X_train, y_train)

LinearRegression()

In [93]:
clr.coeff

array([-0.00380191, -0.00104433,  0.00942596])

In [94]:
sklearn_lr.coef_

array([-0.00380191, -0.00104433,  0.00942596])


Under the hood, sklearn model is:

Class object with model parameters as attributes.

- .fit(X,y) method uses formula or algorithm to find model parameters (weights)
- used X, y as training data

- .predict(X) 
    - learned parameters + X into model
    - get prediction

In [95]:
clr.predict(X_test)[0:5]

172    0.553272
40     0.385155
95     0.170981
285    0.193660
129    0.140494
dtype: float64

In [96]:
sklearn_lr.predict(X_test)[0:5]

array([0.55327231, 0.38515452, 0.17098091, 0.19365998, 0.14049418])

In [98]:
clr.intercept

-0.4377808886139576

In [101]:
sklearn_lr.intercept_

-0.4377808886139338

We showed:
- Clearly how sklearn works under the hood via class objects   
- But not integrated into the scikit-learn library
    


Next: 
- Learn about parent/child classes
- Inheritance and class hierarchy
- Integrate our models/transformers into scikit-learn class hierarchy.